/*Program to display simple messages and values on an LCD screen
Adapted from publically available GITHUB program for an arduino
01/11/23
Version 3
FURTHER MODIFIED BY SAM HOBERN
*/

/* Ensure RW LCD pin is connected to GND and connect a 10 K potentiometer with wiper connected to V0 and other ends to A and K LCD pins.
 Connect a 100 ohm resistor (ideally 500 Ohm) between A LCD pin and VDD.
 */

#include "mbed.h"
#include "TextLCD_CC.h"

int main() 
{
    // Characters can be generated by various online tools
    // 5x8 array.
    char cc1[] = {0x00, 0x00, 0x0A, 0x00, 0x11, 0x0E, 0x00, 0x00};
    int smiley = 0;
    TextLCD lcd(D0, D1, D2, D3, D4, D5, TextLCD::LCD16x2);
    lcd.locate(0,0);
    
    lcd.writeCustomCharacter(cc1, 1);

    lcd.printf("Hello!\n%c", smiley);
    thread_sleep_for(1000);
    lcd.cls();
    lcd.printf("%c I'm Smiley!", smiley);

    while(true){
        sleep();
    }
}